<?php

return [
	'graphql' => [
		'domains' => [
			'attribute' => 'attribute',
			'attribute/type' => 'attribute/type',
			'attribute/lists/type' => 'attribute/lists/type',
			'attribute/property/type' => 'attribute/property/type',
			'catalog' => 'catalog',
			'catalog/lists/type' => 'catalog/lists/type',
			'coupon' => 'coupon',
			'coupon/code' => 'coupon/code',
			'customer' => 'customer',
			'group' => 'group',
			'customer/lists/type' => 'customer/lists/type',
			'customer/property/type' => 'customer/property/type',
			'locale' => 'locale',
			'locale/currency' => 'locale/currency',
			'locale/language' => 'locale/language',
			'locale/site' => 'locale/site',
			'media' => 'media',
			'media/type' => 'media/type',
			'media/lists/type' => 'media/lists/type',
			'media/property/type' => 'media/property/type',
			'order' => 'order',
			'order/status' => 'order/status',
			'plugin' => 'plugin',
			'plugin/type' => 'plugin/type',
			'price' => 'price',
			'price/type' => 'price/type',
			'price/lists/type' => 'price/lists/type',
			'price/property/type' => 'price/property/type',
			'product' => 'product',
			'product/type' => 'product/type',
			'product/lists/type' => 'product/lists/type',
			'product/property/type' => 'product/property/type',
			'review' => 'review',
			'rule' => 'rule',
			'rule/type' => 'rule/type',
			'service' => 'service',
			'service/type' => 'service/type',
			'service/lists/type' => 'service/lists/type',
			'stock' => 'stock',
			'stock/type' => 'stock/type',
			'subscription' => 'subscription',
			'supplier' => 'supplier',
			'supplier/lists/type' => 'supplier/lists/type',
			'tag' => 'tag',
			'tag/type' => 'tag/type',
			'text' => 'text',
			'text/type' => 'text/type',
			'text/lists/type' => 'text/lists/type',
		],
		'lists-domains' => [
			'attribute' => 'attribute',
			'catalog' => 'catalog',
			'customer' => 'customer',
			'group' => 'group',
			'media' => 'media',
			'price' => 'price',
			'product' => 'product',
			'service' => 'service',
			'supplier' => 'supplier',
			'tag' => 'tag',
			'text' => 'text',
		]
	],
];
